"""initial_schema

Revision ID: c661f6b62e0c
Revises: 
Create Date: 2026-02-07 23:26:19.659177

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c661f6b62e0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_heartbeats',
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='idle', nullable=False),
    sa.Column('current_task', sa.Text(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restart_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('email_campaigns',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('target_cities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('target_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('total_leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bounce_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_type', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('client_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills_required', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('disqualify_reason', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_jobs_platform_external_id')
    )
    op.create_index('idx_jobs_platform', 'jobs', ['platform', 'status'], unique=False)
    op.create_index('idx_jobs_score', 'jobs', ['score'], unique=False, postgresql_where="status = 'qualified'")
    op.create_index('idx_jobs_status', 'jobs', ['status', 'discovered_at'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_type', 'knowledge_base', ['type', 'category'], unique=False)
    op.create_table('langgraph_checkpoints',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id')
    )
    op.create_index('idx_checkpoints_thread', 'langgraph_checkpoints', ['thread_id', 'created_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('h3_index', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_source', sa.String(length=20), nullable=True),
    sa.Column('enrichment_cost', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('enrichment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_id')
    )
    op.create_index('idx_leads_city', 'leads', ['city', 'category', 'status'], unique=False)
    op.create_index('idx_leads_h3', 'leads', ['h3_index'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query_hash', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Text(), server_default='default', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_index('idx_cache_expires', 'semantic_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_type', 'semantic_cache', ['query_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='owner', nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('personalized_subject', sa.Text(), nullable=True),
    sa.Column('personalized_body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'lead_id')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accounts_platform', 'platform_accounts', ['platform', 'status'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_text', sa.Text(), nullable=False),
    sa.Column('bid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('portfolio_items', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('hitl_request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('generation_model', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'account_id', name='uq_bids_job_account')
    )
    op.create_index('idx_bids_job', 'bids', ['job_id'], unique=False)
    op.create_index('idx_bids_status', 'bids', ['status'], unique=False)
    op.create_table('ab_test_results',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('variant_id', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('bid_id', sa.Uuid(), nullable=True),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('responses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hires', sa.Integer(), server_default='0', nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('opening_style', sa.String(length=30), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ab_test', 'ab_test_results', ['test_name', 'variant_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=30), server_default='freelance', nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agreed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='planning', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revision_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kanban_column', sa.String(length=30), nullable=True),
    sa.Column('kanban_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_deadline', 'projects', ['deadline'], unique=False, postgresql_where="status NOT IN ('completed', 'cancelled')")
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_type', 'projects', ['type', 'status'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('client_feedback', sa.Text(), nullable=False),
    sa.Column('parsed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('assigned_agent', sa.String(length=30), nullable=True),
    sa.Column('hitl_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('tasks_created', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_revisions_project', 'revisions', ['project_id', 'status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('depends_on', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('artifact_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_agent', 'tasks', ['assigned_agent', 'status'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id', 'status'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_agent', 'agent_logs', ['agent_name', 'created_at'], unique=False)
    op.create_index('idx_agent_logs_event', 'agent_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_agent_logs_project', 'agent_logs', ['project_id', 'created_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), server_default='db', nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('generated_by', sa.String(length=30), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('security_scan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['previous_version_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_project', 'artifacts', ['project_id'], unique=False)
    op.create_index('idx_artifacts_type', 'artifacts', ['type'], unique=False)
    op.create_table('hitl_queue',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_actions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hitl_status', 'hitl_queue', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('idx_hitl_type', 'hitl_queue', ['type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hitl_type', table_name='hitl_queue')
    op.drop_index('idx_hitl_status', table_name='hitl_queue')
    op.drop_table('hitl_queue')
    op.drop_index('idx_artifacts_type', table_name='artifacts')
    op.drop_index('idx_artifacts_project', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_agent_logs_project', table_name='agent_logs')
    op.drop_index('idx_agent_logs_event', table_name='agent_logs')
    op.drop_index('idx_agent_logs_agent', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_agent', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_revisions_project', table_name='revisions')
    op.drop_table('revisions')
    op.drop_index('idx_projects_type', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_deadline', table_name='projects', postgresql_where="status NOT IN ('completed', 'cancelled')")
    op.drop_table('projects')
    op.drop_index('idx_ab_test', table_name='ab_test_results')
    op.drop_table('ab_test_results')
    op.drop_index('idx_bids_status', table_name='bids')
    op.drop_index('idx_bids_job', table_name='bids')
    op.drop_table('bids')
    op.drop_index('idx_accounts_platform', table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_table('campaign_leads')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_cache_type', table_name='semantic_cache')
    op.drop_index('idx_cache_expires', table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_h3', table_name='leads')
    op.drop_index('idx_leads_city', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_checkpoints_thread', table_name='langgraph_checkpoints')
    op.drop_table('langgraph_checkpoints')
    op.drop_index('idx_knowledge_type', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_score', table_name='jobs', postgresql_where="status = 'qualified'")
    op.drop_index('idx_jobs_platform', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('email_campaigns')
    op.drop_table('agent_heartbeats')
    # ### end Alembic commands ###
