"""Pydantic v2 models for all agent outputs.

Every agent that parses LLM JSON should validate against these schemas.
Using Pydantic v2 ensures type safety and clear error messages when
the LLM returns structurally unexpected data.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Scout Agent
# ---------------------------------------------------------------------------


class ScoutScoredJob(BaseModel):
    """A job scored and classified by the Scout Agent."""

    job_id: str | None = Field(default=None, alias="job_id")
    title: str = ""
    match_score: float = Field(default=0.0, alias="match_score")
    recommendation: Literal["bid", "skip", "review"] = "skip"
    reasoning: str = ""
    skills_match: list[str] = Field(default_factory=list)

    # Pass through any extra fields from the LLM
    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Bid Agent
# ---------------------------------------------------------------------------


class BidProposal(BaseModel):
    """A proposal generated by the Bid Agent."""

    proposal_text: str
    bid_amount: float = Field(alias="bid_amount")
    delivery_days: int = Field(default=7, alias="delivery_days")
    confidence_score: float = Field(default=0.5, alias="confidence_score")
    key_points: list[str] = Field(default_factory=list)
    milestones: list[dict[str, Any]] = Field(default_factory=list)
    requires_hitl: bool = True

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Planner Agent
# ---------------------------------------------------------------------------


class PlanStep(BaseModel):
    """A single task in a project plan."""

    id: str = ""
    description: str = ""
    assigned_to: str = Field(default="dev", alias="assigned_to")
    estimated_hours: float = Field(default=1.0, alias="estimated_hours")
    dependencies: list[str] = Field(default_factory=list)
    deliverables: list[str] = Field(default_factory=list)

    model_config = {"extra": "allow", "populate_by_name": True}


class PlanPhase(BaseModel):
    """A phase in a project plan, containing multiple tasks."""

    name: str = ""
    tasks: list[PlanStep] = Field(default_factory=list)

    model_config = {"extra": "allow", "populate_by_name": True}


class PlannerPlan(BaseModel):
    """A complete project plan generated by the Planner Agent."""

    phases: list[PlanPhase] = Field(default_factory=list)
    total_estimated_hours: float = Field(default=0.0, alias="total_estimated_hours")
    critical_path: list[str] = Field(default_factory=list, alias="critical_path")
    risks: list[str] = Field(default_factory=list)
    complexity: str = ""

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Dev Agent
# ---------------------------------------------------------------------------


class CodeFile(BaseModel):
    """A single generated code file."""

    path: str
    content: str
    language: str = ""

    model_config = {"extra": "allow", "populate_by_name": True}


class DevCodeOutput(BaseModel):
    """Code output generated by the Dev Agent."""

    files: list[CodeFile]
    dependencies: list[str] = Field(default_factory=list)
    build_commands: list[str] = Field(default_factory=list, alias="build_commands")
    test_commands: list[str] = Field(default_factory=list, alias="test_commands")
    deployment_notes: str = Field(default="", alias="deployment_notes")
    tests_included: bool = False

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Content Agent
# ---------------------------------------------------------------------------


class ContentDeliverable(BaseModel):
    """Content output generated by the Content Agent."""

    content_type: str = Field(default="landing_page", alias="content_type")
    deliverables: list[dict[str, Any]] = Field(default_factory=list)
    word_count: int = Field(default=0, alias="word_count")
    reading_time_seconds: int = Field(default=0, alias="reading_time_seconds")
    meta: dict[str, Any] = Field(default_factory=dict)

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Design Agent
# ---------------------------------------------------------------------------


class DesignSpec(BaseModel):
    """Design specification generated by the Design Agent."""

    design_type: str = Field(default="ui_mockup", alias="design_type")
    deliverables: list[dict[str, Any]] = Field(default_factory=list)
    components: list[dict[str, Any]] = Field(default_factory=list)
    layout: str = ""
    colors: list[str] = Field(default_factory=list)
    fonts: list[str] = Field(default_factory=list)

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Critic Agent
# ---------------------------------------------------------------------------


class CriticIssue(BaseModel):
    """A single issue found during code/content review."""

    type: str = ""
    severity: str = "medium"
    description: str = ""
    location: str = ""

    model_config = {"extra": "allow", "populate_by_name": True}


class CriticVerdict(BaseModel):
    """Quality review verdict from the Critic Agent."""

    verdict: Literal["approve", "revise", "reject"] = "reject"
    score: float = Field(default=0.0, ge=0.0, le=1.0)
    issues: list[CriticIssue] = Field(default_factory=list)
    passed_checks: list[str] = Field(default_factory=list, alias="passed_checks")
    failed_checks: list[str] = Field(default_factory=list, alias="failed_checks")
    revision_instructions: str = Field(default="", alias="revision_instructions")
    revision_type: Literal["minor", "major", "scope_creep", "none"] = "none"
    recommendation: str = ""

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Packager Agent
# ---------------------------------------------------------------------------


class PackageManifest(BaseModel):
    """Delivery package manifest from the Packager Agent."""

    delivery_id: str = ""
    project_id: str = Field(default="unknown", alias="project_id")
    files_count: int = Field(default=0, alias="files_count")
    includes: list[str] = Field(default_factory=list)
    delivery_message: str = Field(
        default="Your project delivery is ready for review.",
        alias="delivery_message",
    )
    readme_content: str = Field(default="", alias="readme_content")
    missing_artifacts: list[str] = Field(default_factory=list, alias="missing_artifacts")
    quality_notes: str = Field(default="", alias="quality_notes")
    deployment_notes: str = ""
    requires_hitl: bool = True

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Pipeline B: Geo Scout Agent
# ---------------------------------------------------------------------------


class GeoScoutBusiness(BaseModel):
    """A single business discovered by the Geo Scout Agent."""

    name: str
    category: str = ""
    address: str = ""
    lat: float = 0.0
    lon: float = 0.0
    phone: str = ""
    osm_id: int = 0

    model_config = {"extra": "allow", "populate_by_name": True}


class GeoScoutResult(BaseModel):
    """Result of a geo scan from the Geo Scout Agent."""

    businesses: list[GeoScoutBusiness] = Field(default_factory=list)
    scan_area: str = ""
    total_found: int = 0

    model_config = {"extra": "allow", "populate_by_name": True}


# ---------------------------------------------------------------------------
# Pipeline B: Outreach Agent
# ---------------------------------------------------------------------------


class OutreachEmail(BaseModel):
    """A cold email generated by the Outreach Agent."""

    subject: str
    body: str
    personalization_score: float = Field(default=0.0, alias="personalization_score")
    template_vars: dict[str, Any] = Field(default_factory=dict, alias="template_vars")

    model_config = {"extra": "allow", "populate_by_name": True}
